version: "3.8"

services:
  flask-app:
    image: momina07/flask-calculator:latest  # Using our Docker Hub image
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: always  # Automatically restarts the container if it stops

